# Generated by Django 6.0.7 on 2026-07-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dealerreview",
            old_name="review",
            new_name="review_text",
        ),
        migrations.RenameField(
            model_name="dealerreview",
            old_name="name",
            new_name="reviewer_name",
        ),
        migrations.RemoveField(
            model_name="dealerreview",
            name="created_at",
        ),
        migrations.AddField(
            model_name="dealer",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dealer",
            name="long",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dealer",
            name="short_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="dealer",
            name="zip",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dealerreview",
            name="car_make",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dealerreview",
            name="car_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dealerreview",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
